scr_initialize_ai_components(BLUE, scr_ai_set_temperment_meanie);
scr_initialize_character(obj_character_sheet_1, obj_profile_p1);
scr_initialize_character_sprite(scr_set_sprite_exil, scr_set_sprite_hair);
scr_set_nutrition_values(100, 100, 100, 100, 100, 100);
scr_inv_item_add_spear();
scr_inv_item_add_shield();
scr_inv_item_add_bow();
scr_inv_item_add_arrow();
scr_inv_clothes_add_bag();
scr_inv_clothes_add_bandana();
scr_inv_clothes_add_shirt();
scr_inv_clothes_add_shorts();
